folders:
  parent_dir: "./results/"
  model_name: "sf3_p1_vs_ai_ppo"

settings:
  game_id: "sfiii3n"
  step_ratio: 6
  frame_shape: !!python/tuple [224, 384, 1]
  continue_game: 0.0
  action_space: "discrete"
  characters: "Urien"
  outfits: 2
  role: 2 
  n_players: 1 
  difficulty: 3
  disable_joystick: true
  disable_keyboard: true

wrappers_settings:
  normalize_reward: true
  no_attack_buttons_combinations: true
  stack_frames: 1
  dilation: 1
  add_last_action: true
  stack_actions: 8
  scale: true
  exclude_image_scaling: true
  role_relative: true
  flatten: true
  filter_keys:
    [
      "action",
      "own_health",
      "opp_health",
      "own_side",
      "opp_side",
      "opp_character",
      "stage",
      "timer",
    ]

policy_kwargs:
  net_arch: [256, 256]

ppo_settings:
  gamma: 0.99
  model_checkpoint: "0"
  learning_rate: [2.5e-4, 2.5e-6]
  clip_range: [0.2, 0.1]
  batch_size: 128
  n_epochs: 10
  n_steps: 2048
  autosave_freq: 50000
  time_steps: 2000000
